name: reservili
description: "Reservili - Home reservation management app."
publish_to: "none"
version: 1.0.0+4318

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.5.1

  # Navigation
  go_router: ^14.2.0

  # Networking
  dio: ^5.5.0

  # Local storage (auth token, preferences)
  shared_preferences: ^2.2.0

  # Device ID (for access code + device binding)
  device_info_plus: ^10.1.0

  # Dates & i18n formatting
  intl: ^0.20.2

  # Nice-to-have UI
  cupertino_icons: ^1.0.8

  # Notifications
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  flutter_timezone: ^3.0.1

  # Local database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  intl_utils: ^2.8.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "Logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "Logo.png"
  remove_alpha_ios: true

